/*
 * Pact MP-1 - brand tokens as LVGL values (docs/brand-ui-system.md,
 * docs/asset-pipeline.md section 4).
 *
 * Monochrome by design: color exists only in album art and the battery fill.
 */
#pragma once
#include "lvgl.h"

#define PACT_COL_GROUND    lv_color_hex(0x000000) /* true black - AMOLED off  */
#define PACT_COL_TEXT      lv_color_hex(0xF4F3EF) /* warm white               */
#define PACT_COL_TEXT_DIM  lv_color_hex(0x8A887F) /* secondary grey           */
#define PACT_COL_SELECT    lv_color_hex(0x1A1A1A) /* subtle selection fill    */
#define PACT_COL_WHITE     lv_color_hex(0xFFFFFF) /* progress bar / LED mirror */
#define PACT_COL_BATT_LOW  lv_color_hex(0xE04030) /* battery <15% - the ONLY red */

/* Baked Diatype cuts (App/ui/assets/, generated by lv_font_conv) */
LV_FONT_DECLARE(diatype_regular_22); /* menu rows / body        */
LV_FONT_DECLARE(diatype_regular_24); /* now-playing artist/album */
LV_FONT_DECLARE(diatype_medium_32);  /* now-playing title        */
LV_FONT_DECLARE(scotch_mono_16);     /* times / format badges (trial mono) */

/* Motion: snap, ease, done. */
#define PACT_ANIM_MS 180
